server:
  servlet:
    context-path: /
  port: 8080
  compression:
    mime-types:
      - application/json

spring:
  application:
    name: subscription-service
  main:
    allow-bean-definition-overriding: true
#Remove this feature to enable database connections
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      -
  # Enabling database connection
  datasource:
    url: jdbc:mysql://localhost:3306/subscription
    username: root
    password: subscription

  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.mysql
    properties:
      hibernate:
        jdbc:
          batch_size: 50

#config liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-local.xml
    url: jdbc:mysql://localhost:3306/subscription
    user: root
    password: subscription
    changeLogFile: classpath:db/changelog/changelog-local.xml

## Enabling rabbitmq

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: <username>
#    password: <password>
#    cache:
#      connection:
#        mode: CONNECTION
#      channel:
#        size: 50
#      checkout-timeout: 10000
